<<<<<<< HEAD
# Generated by Django 2.1 on 2018-08-28 21:29
=======
# Generated by Django 2.2.4 on 2019-09-10 19:11
>>>>>>> origin/master

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('image', models.ImageField(default='default.jpg', upload_to='profile_pics')),
=======
                ('image', models.ImageField(default='defaut.jpg', upload_to='profile_pics')),
>>>>>>> origin/master
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
